### PR TITLE
Fix and test JADE.simulate

### LINKED ISSUE #36: Historical simulation is untested and broken
Fixed a couple of things locally that I'll make a PR for in a bit. But:
```Julia
function test_case_1_simulate()
    optimizer = MOI.OptimizerWithAttributes(HiGHS.Optimizer, MOI.Silent() => true)
    data = define_JADE_model("test1");
    data.use_terminal_mwvs = true
    solve_options = define_JADE_solve_options("test1");
    model = create_JADE_model(data, optimizer);
    optimize_policy!(model, solve_options; print_level = 0);

    simulation = define_JADE_simulation("test1");
    simulation.sim_type = :historical
    @test_throws(
        ErrorException("Invalid settings found. See REPL for details."),
        JADE.simulate(model, simulation),
    )
    simulation.sim_years = [2008]
    @test_throws(
        ErrorException("Invalid settings found. See REPL for details."),
        JADE.simulate(model, simulation),
    )
    simulation.replications = 1
    results = JADE.simulate(model, simulation)
end


ERROR: KeyError: key 45 not found
Stacktrace:
  [1] getindex
    @ ./dict.jl:482 [inlined]
  [2] getindex
    @ ~/.julia/packages/SDDP/OoTfR/src/user_interface.jl:516 [inlined]
  [3] _simulate(model::SDDP.PolicyGraph{Int64}, variables::Vector{Symbol}; sampling_scheme::SDDP.Historical{Int64, Dict{Symbol, Float64}}, custom_recorders::Dict{Symbol, Function}, duality_handler::Nothing, skip_undefined_variables::Bool, incoming_state::Dict{Symbol, Float64})
    @ SDDP ~/.julia/packages/SDDP/OoTfR/src/algorithm.jl:1099
  [4] #208
    @ ~/.julia/packages/SDDP/OoTfR/src/plugins/parallel_schemes.jl:50 [inlined]
  [5] iterate
    @ ./generator.jl:47 [inlined]
  [6] _collect(c::UnitRange{Int64}, itr::Base.Generator{UnitRange{Int64}, SDDP.var"#208#209"{Base.Iterators.Pairs{Symbol, Any, NTuple{5, Symbol}, NamedTuple{(:sampling_scheme, :custom_recorders, :duality_handler, :skip_undefined_variables, :incoming_state), Tuple{SDDP.Historical{Int64, Dict{Symbol, Float64}}, Dict{Symbol, Function}, Nothing, Bool, Dict{Symbol, Float64}}}}, SDDP.PolicyGraph{Int64}, Vector{Symbol}}}, #unused#::Base.EltypeUnknown, isz::Base.HasShape{1})
    @ Base ./array.jl:695
  [7] collect_similar
    @ ./array.jl:606 [inlined]
  [8] map
    @ ./abstractarray.jl:2294 [inlined]
  [9] #_simulate#207
    @ ~/.julia/packages/SDDP/OoTfR/src/plugins/parallel_schemes.jl:49 [inlined]
 [10] #simulate#82
    @ ~/.julia/packages/SDDP/OoTfR/src/algorithm.jl:1274 [inlined]
 [11] simulate(JADEmodel::JADE.JADEModel, parameters::JADE.JADESimulation)
    @ JADE ~/.julia/dev/JADE/src/simulate.jl:279
 [12] top-level scope
    @ REPL[41]:1
```

### LINKED ISSUE #39: Use of private SDDP function
Just found this one:
https://github.com/EPOC-NZ/JADE.jl/blob/79b364d8ce6eb64c5d615e970bf881105e85b703/src/simulate.jl#L94

It looks like it's the only instance left in `develop`.

### PR DESCRIPTION
**Pull request by odow**
I guess the most important question is: am I using the API correctly? This change fixed https://github.com/EPOC-NZ/JADE.jl/issues/36, but I don't know if it was something else I was doing wrong.

Closes https://github.com/EPOC-NZ/JADE.jl/issues/36
Closes https://github.com/EPOC-NZ/JADE.jl/issues/39

### CODE REVIEW

File: src/simulate.jl [hunk 1]
```diff
@@ -271,10 +270,7 @@ function simulate(JADEmodel::JADEModel, parameters::JADESimulation)
                     if (t + d.rundata.start_wk - 2) % WEEKSPERYEAR == WEEKSPERYEAR - 1
                         i += 1
                     end
-                    push!(
-                        sample_paths[end],
-                        ((t + d.rundata.start_wk - 2) % WEEKSPERYEAR + 1, s_inflows),
-                    )
+                    push!(sample_paths[end], (t, s_inflows))
```
Comment (odow) [inline src/simulate.jl]: The node in the sample path needs to be the node in the SDDP graph. I think `t` here is `1:20`, where as the previous was the actual week, `vcat(45:52,1:13)`? Is it true that nodes in SDDP are always `1..T`?

File: test/test_cases.jl [hunk 2]
```diff
@@ -298,6 +298,58 @@ function test_case_1_infinite_horizon_then_finite_horizon()
...
+    @test_throws(
+        ErrorException("Invalid settings found. See REPL for details."),
+        JADE.simulate(model, simulation),
+    )
+    simulation.replications = 1
+    results = JADE.simulate(model, simulation)
+    @test length(results) == 1
+    @test length(results[1]) == 20
+    @test sum(results[1][1][:lostload]) ≈ 0.0
+    @test results[1][1][:inflow][:LAKE_AVIEMORE] == 16.2042285714286
```
Comment (odow) [inline test/test_cases.jl:324]: I'm not sure how to check for solutions that make sense, so I just checked we at least used the right inflow sequence.

File: src/simulate.jl (hunk 1 above)
Comment (adow031) [reply src/simulate.jl]: Something about this looks messed up, but perhaps there's something tricky going on that I've forgotten about. I'll dig into tomorrow; don't spend any time on this in the meantime.

Comment (adow031) [reply src/simulate.jl]: I found the commit that broke this on January 26 2022, from the private JADE repo.

I think that it needs to be:
`push!(sample_paths[end], ((t - 1) % WEEKSPERYEAR + 1, s_inflows))`,
in order to be able to wrap around for infinite-horizon models (i.e. if we wish to simulate an infinite horizon model from stage 26, for 52 weeks, then the stages should be 26,...,52,1,...,25.

However, I need to do some tests to ensure that errors are being appropriately thrown if the model isn't set up right.

Comment (odow) [reply src/simulate.jl]: How do I create a test that will trip this? I'm very confused as to how the JADE and SDDP week/indices line up.

Comment (adow031) [reply src/simulate.jl]: The `rundata.start_wk` parameter is the first week of the model, this will correspond to stage 1 of the SDDP model.

The `parameters.initial_stage` is the starting stage of the simulation (the initial states will be injected into this stage and the simulation will continue from this stage). This could have been made easier for the user and implemented as `initial_week`, but it was getting quite confusing...so this wasn't done. The `initial_stage` parameter will typically be left at 1.

I should be able to create a test for this; it probably can be done with a one/two period model, and the cost of an untrained model will change as the parameters vary.

**Review by adow031 — APPROVED** [review]
Looks good.
